//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTeste
{
    using System;
    using System.Collections.Generic;
    
    public partial class LancamentoHoras
    {
        public int Id { get; set; }
        public System.DateTime DataInicial { get; set; }
        public System.DateTime DataFinal { get; set; }
        public int DesenvolvedorId { get; set; }
        public int ProjetoId { get; set; }
    
        public virtual Desenvolvedor Desenvolvedor { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
