//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTeste
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbLancamentoHorasEntities : DbContext
    {
        public DbLancamentoHorasEntities()
            : base("name=DbLancamentoHorasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Desenvolvedor> Desenvolvedor { get; set; }
        public virtual DbSet<LancamentoHoras> LancamentoHoras { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
    }
}
